net.Receive( "DamagedKill", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "nz/"..charactername.."/Zombie/damaged"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "CloseKill", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "nz/"..charactername.."/Zombie/close"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "Headshot", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "nz/"..charactername.."/Zombie/headshot"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "MonkeyKill", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "nz/"..charactername.."/Zombie/monkey_kill"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "ExplosiveKill", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "nz/"..charactername.."/Zombie/explosion"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "Insta", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "nz/"..charactername.."/Zombie/instakill"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "Raygun", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "nz/"..charactername.."/Zombie/raygun_kill"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "Thundergun", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "nz/"..charactername.."/Zombie/thundergun_kill"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "Killstreak", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "nz/"..charactername.."/Zombie/streak"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )