net.Receive( "DamagedKill", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "sound/path"..charactername.."sound/path"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "CloseKill", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "sound/path"..charactername.."sound/path"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "Headshot", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "sound/path"..charactername.."sound/path"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "MonkeyKill", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "sound/path"..charactername.."sound/path"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "ExplosiveKill", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "sound/path"..charactername.."sound/path"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "Insta", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "sound/path"..charactername.."sound/path"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "Raygun", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "sound/path"..charactername.."sound/path"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "Thundergun", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "sound/path"..charactername.."sound/path"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "Killstreak", function()
    local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "sound/path"..charactername.."sound/path"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )