
net.Receive( "SayReviveDown", function()
	local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "nz/"..charactername.."/Revive/down"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )

net.Receive( "SayReviveUp", function()
	local number = net.ReadInt()
	whatsmyname()
	timer.Simple( 0.9, function()
		sound.Play( "nz/"..charactername.."/Revive/up"..number..".ogg", self:GetPos(), 75, 100, 1 )
	end )
end )